/**
 * The resolved transition table, one line per (state, input) pair.
 *
 * GENERATED-BY-REVIEW: this file is written by hand-checking the output of
 * `describeTransitionTable()`. `table.test.ts` asserts the machine still
 * produces exactly this, so any change to the table shows up here as a diff a
 * reviewer can read without reading the code.
 *
 * Format: `<state> + <input> -> <targets>[ | reject(<reasons>)]`, where
 * `resting` is `restingState(context)` and `same` means the state does not
 * change. A cell with no target is a hard rejection.
 */
export const EXPECTED_TRANSITION_TABLE: readonly string[] = [
  'idle + select-window -> resting | reject(window-not-found,illegal-transition)',
  'idle + set-observation-enabled -> resting | reject(illegal-transition)',
  'idle + push-to-talk-down -> listening | reject(illegal-transition)',
  'idle + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'idle + submit-text -> thinking | reject(empty-input)',
  'idle + look-now -> observing-screen | reject(illegal-transition)',
  'idle + interrupt -> resting | reject(nothing-to-interrupt)',
  'idle + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'idle + clear-conversation -> resting',
  'idle + pause -> resting | reject(already-paused)',
  'idle + resume -> resting | reject(not-paused)',
  'idle + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'idle + permissions-changed -> resting|same',
  'idle + windows-changed -> same',
  'idle + window-closed -> error',
  'idle + screen-locked -> resting | reject(illegal-transition)',
  'idle + screen-unlocked -> resting | reject(illegal-transition)',
  'idle + transcript-partial -> reject(illegal-transition)',
  'idle + transcript-final -> reject(illegal-transition)',
  'idle + transcript-failed -> reject(illegal-transition)',
  'idle + run-started -> reject(illegal-transition)',
  'idle + run-text-delta -> reject(illegal-transition)',
  'idle + tool-started -> reject(illegal-transition)',
  'idle + tool-finished -> reject(illegal-transition)',
  'idle + run-completed -> reject(illegal-transition)',
  'idle + run-aborted -> reject(illegal-transition)',
  'idle + run-failed -> reject(illegal-transition)',
  'idle + observation-finished -> reject(illegal-transition)',
  'idle + speech-started -> reject(illegal-transition)',
  'idle + speech-finished -> reject(illegal-transition)',
  'idle + speech-stopped -> reject(illegal-transition)',
  'idle + speech-failed -> reject(illegal-transition)',
  'idle + failure -> error',
  'needs-permission + select-window -> reject(not-permitted)',
  'needs-permission + set-observation-enabled -> reject(not-permitted)',
  'needs-permission + push-to-talk-down -> reject(not-permitted)',
  'needs-permission + push-to-talk-up -> reject(not-permitted)',
  'needs-permission + submit-text -> reject(not-permitted)',
  'needs-permission + look-now -> reject(not-permitted)',
  'needs-permission + interrupt -> reject(not-permitted)',
  'needs-permission + stop-speaking -> reject(not-permitted)',
  'needs-permission + clear-conversation -> resting',
  'needs-permission + pause -> resting | reject(already-paused)',
  'needs-permission + resume -> resting | reject(not-paused)',
  'needs-permission + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'needs-permission + permissions-changed -> resting|same',
  'needs-permission + windows-changed -> same',
  'needs-permission + window-closed -> error',
  'needs-permission + screen-locked -> resting | reject(illegal-transition)',
  'needs-permission + screen-unlocked -> resting | reject(illegal-transition)',
  'needs-permission + transcript-partial -> reject(illegal-transition)',
  'needs-permission + transcript-final -> reject(illegal-transition)',
  'needs-permission + transcript-failed -> reject(illegal-transition)',
  'needs-permission + run-started -> reject(illegal-transition)',
  'needs-permission + run-text-delta -> reject(illegal-transition)',
  'needs-permission + tool-started -> reject(illegal-transition)',
  'needs-permission + tool-finished -> reject(illegal-transition)',
  'needs-permission + run-completed -> reject(illegal-transition)',
  'needs-permission + run-aborted -> reject(illegal-transition)',
  'needs-permission + run-failed -> reject(illegal-transition)',
  'needs-permission + observation-finished -> reject(illegal-transition)',
  'needs-permission + speech-started -> reject(illegal-transition)',
  'needs-permission + speech-finished -> reject(illegal-transition)',
  'needs-permission + speech-stopped -> reject(illegal-transition)',
  'needs-permission + speech-failed -> reject(illegal-transition)',
  'needs-permission + failure -> error',
  'paused + select-window -> reject(paused)',
  'paused + set-observation-enabled -> reject(paused)',
  'paused + push-to-talk-down -> reject(paused)',
  'paused + push-to-talk-up -> reject(paused)',
  'paused + submit-text -> reject(paused)',
  'paused + look-now -> reject(paused)',
  'paused + interrupt -> reject(paused)',
  'paused + stop-speaking -> reject(paused)',
  'paused + clear-conversation -> resting',
  'paused + pause -> resting | reject(already-paused)',
  'paused + resume -> resting | reject(not-paused)',
  'paused + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'paused + permissions-changed -> resting|same',
  'paused + windows-changed -> same',
  'paused + window-closed -> error',
  'paused + screen-locked -> resting | reject(illegal-transition)',
  'paused + screen-unlocked -> resting | reject(illegal-transition)',
  'paused + transcript-partial -> reject(illegal-transition)',
  'paused + transcript-final -> reject(illegal-transition)',
  'paused + transcript-failed -> reject(illegal-transition)',
  'paused + run-started -> reject(illegal-transition)',
  'paused + run-text-delta -> reject(illegal-transition)',
  'paused + tool-started -> reject(illegal-transition)',
  'paused + tool-finished -> reject(illegal-transition)',
  'paused + run-completed -> reject(illegal-transition)',
  'paused + run-aborted -> reject(illegal-transition)',
  'paused + run-failed -> reject(illegal-transition)',
  'paused + observation-finished -> reject(illegal-transition)',
  'paused + speech-started -> reject(illegal-transition)',
  'paused + speech-finished -> reject(illegal-transition)',
  'paused + speech-stopped -> reject(illegal-transition)',
  'paused + speech-failed -> reject(illegal-transition)',
  'paused + failure -> error',
  'observing + select-window -> resting | reject(window-not-found,illegal-transition)',
  'observing + set-observation-enabled -> resting | reject(illegal-transition)',
  'observing + push-to-talk-down -> listening | reject(illegal-transition)',
  'observing + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'observing + submit-text -> thinking | reject(empty-input)',
  'observing + look-now -> observing-screen | reject(illegal-transition)',
  'observing + interrupt -> resting | reject(nothing-to-interrupt)',
  'observing + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'observing + clear-conversation -> resting',
  'observing + pause -> resting | reject(already-paused)',
  'observing + resume -> resting | reject(not-paused)',
  'observing + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'observing + permissions-changed -> resting|same',
  'observing + windows-changed -> same',
  'observing + window-closed -> error',
  'observing + screen-locked -> resting | reject(illegal-transition)',
  'observing + screen-unlocked -> resting | reject(illegal-transition)',
  'observing + transcript-partial -> reject(illegal-transition)',
  'observing + transcript-final -> reject(illegal-transition)',
  'observing + transcript-failed -> reject(illegal-transition)',
  'observing + run-started -> reject(illegal-transition)',
  'observing + run-text-delta -> reject(illegal-transition)',
  'observing + tool-started -> reject(illegal-transition)',
  'observing + tool-finished -> reject(illegal-transition)',
  'observing + run-completed -> reject(illegal-transition)',
  'observing + run-aborted -> reject(illegal-transition)',
  'observing + run-failed -> reject(illegal-transition)',
  'observing + observation-finished -> reject(illegal-transition)',
  'observing + speech-started -> reject(illegal-transition)',
  'observing + speech-finished -> reject(illegal-transition)',
  'observing + speech-stopped -> reject(illegal-transition)',
  'observing + speech-failed -> reject(illegal-transition)',
  'observing + failure -> error',
  'listening + select-window -> resting | reject(window-not-found,illegal-transition)',
  'listening + set-observation-enabled -> resting | reject(illegal-transition)',
  'listening + push-to-talk-down -> listening | reject(illegal-transition)',
  'listening + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'listening + submit-text -> thinking | reject(empty-input)',
  'listening + look-now -> observing-screen | reject(illegal-transition)',
  'listening + interrupt -> resting | reject(nothing-to-interrupt)',
  'listening + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'listening + clear-conversation -> resting',
  'listening + pause -> resting | reject(already-paused)',
  'listening + resume -> resting | reject(not-paused)',
  'listening + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'listening + permissions-changed -> resting|same',
  'listening + windows-changed -> same',
  'listening + window-closed -> error',
  'listening + screen-locked -> resting | reject(illegal-transition)',
  'listening + screen-unlocked -> resting | reject(illegal-transition)',
  'listening + transcript-partial -> same',
  'listening + transcript-final -> thinking',
  'listening + transcript-failed -> error',
  'listening + run-started -> reject(illegal-transition)',
  'listening + run-text-delta -> reject(illegal-transition)',
  'listening + tool-started -> reject(illegal-transition)',
  'listening + tool-finished -> reject(illegal-transition)',
  'listening + run-completed -> reject(illegal-transition)',
  'listening + run-aborted -> reject(illegal-transition)',
  'listening + run-failed -> reject(illegal-transition)',
  'listening + observation-finished -> reject(illegal-transition)',
  'listening + speech-started -> reject(illegal-transition)',
  'listening + speech-finished -> reject(illegal-transition)',
  'listening + speech-stopped -> reject(illegal-transition)',
  'listening + speech-failed -> reject(illegal-transition)',
  'listening + failure -> error',
  'transcribing + select-window -> resting | reject(window-not-found,illegal-transition)',
  'transcribing + set-observation-enabled -> resting | reject(illegal-transition)',
  'transcribing + push-to-talk-down -> listening | reject(illegal-transition)',
  'transcribing + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'transcribing + submit-text -> thinking | reject(empty-input)',
  'transcribing + look-now -> observing-screen | reject(illegal-transition)',
  'transcribing + interrupt -> resting | reject(nothing-to-interrupt)',
  'transcribing + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'transcribing + clear-conversation -> resting',
  'transcribing + pause -> resting | reject(already-paused)',
  'transcribing + resume -> resting | reject(not-paused)',
  'transcribing + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'transcribing + permissions-changed -> resting|same',
  'transcribing + windows-changed -> same',
  'transcribing + window-closed -> error',
  'transcribing + screen-locked -> resting | reject(illegal-transition)',
  'transcribing + screen-unlocked -> resting | reject(illegal-transition)',
  'transcribing + transcript-partial -> same',
  'transcribing + transcript-final -> thinking',
  'transcribing + transcript-failed -> error',
  'transcribing + run-started -> reject(illegal-transition)',
  'transcribing + run-text-delta -> reject(illegal-transition)',
  'transcribing + tool-started -> reject(illegal-transition)',
  'transcribing + tool-finished -> reject(illegal-transition)',
  'transcribing + run-completed -> reject(illegal-transition)',
  'transcribing + run-aborted -> reject(illegal-transition)',
  'transcribing + run-failed -> reject(illegal-transition)',
  'transcribing + observation-finished -> reject(illegal-transition)',
  'transcribing + speech-started -> reject(illegal-transition)',
  'transcribing + speech-finished -> reject(illegal-transition)',
  'transcribing + speech-stopped -> reject(illegal-transition)',
  'transcribing + speech-failed -> reject(illegal-transition)',
  'transcribing + failure -> error',
  'thinking + select-window -> resting | reject(window-not-found,illegal-transition)',
  'thinking + set-observation-enabled -> resting | reject(illegal-transition)',
  'thinking + push-to-talk-down -> listening | reject(illegal-transition)',
  'thinking + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'thinking + submit-text -> thinking | reject(empty-input)',
  'thinking + look-now -> observing-screen | reject(illegal-transition)',
  'thinking + interrupt -> resting | reject(nothing-to-interrupt)',
  'thinking + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'thinking + clear-conversation -> resting',
  'thinking + pause -> resting | reject(already-paused)',
  'thinking + resume -> resting | reject(not-paused)',
  'thinking + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'thinking + permissions-changed -> resting|same',
  'thinking + windows-changed -> same',
  'thinking + window-closed -> error',
  'thinking + screen-locked -> resting | reject(illegal-transition)',
  'thinking + screen-unlocked -> resting | reject(illegal-transition)',
  'thinking + transcript-partial -> reject(illegal-transition)',
  'thinking + transcript-final -> reject(illegal-transition)',
  'thinking + transcript-failed -> reject(illegal-transition)',
  'thinking + run-started -> same',
  'thinking + run-text-delta -> same',
  'thinking + tool-started -> observing-screen',
  'thinking + tool-finished -> reject(illegal-transition)',
  'thinking + run-completed -> speaking|resting|same',
  'thinking + run-aborted -> resting',
  'thinking + run-failed -> error',
  'thinking + observation-finished -> reject(illegal-transition)',
  'thinking + speech-started -> speaking',
  'thinking + speech-finished -> reject(illegal-transition)',
  'thinking + speech-stopped -> reject(illegal-transition)',
  'thinking + speech-failed -> reject(illegal-transition)',
  'thinking + failure -> error',
  'observing-screen + select-window -> resting | reject(window-not-found,illegal-transition)',
  'observing-screen + set-observation-enabled -> resting | reject(illegal-transition)',
  'observing-screen + push-to-talk-down -> listening | reject(illegal-transition)',
  'observing-screen + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'observing-screen + submit-text -> thinking | reject(empty-input)',
  'observing-screen + look-now -> observing-screen | reject(illegal-transition)',
  'observing-screen + interrupt -> resting | reject(nothing-to-interrupt)',
  'observing-screen + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'observing-screen + clear-conversation -> resting',
  'observing-screen + pause -> resting | reject(already-paused)',
  'observing-screen + resume -> resting | reject(not-paused)',
  'observing-screen + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'observing-screen + permissions-changed -> resting|same',
  'observing-screen + windows-changed -> same',
  'observing-screen + window-closed -> error',
  'observing-screen + screen-locked -> resting | reject(illegal-transition)',
  'observing-screen + screen-unlocked -> resting | reject(illegal-transition)',
  'observing-screen + transcript-partial -> reject(illegal-transition)',
  'observing-screen + transcript-final -> reject(illegal-transition)',
  'observing-screen + transcript-failed -> reject(illegal-transition)',
  'observing-screen + run-started -> same',
  'observing-screen + run-text-delta -> same',
  'observing-screen + tool-started -> reject(illegal-transition)',
  'observing-screen + tool-finished -> thinking',
  'observing-screen + run-completed -> speaking|resting|same',
  'observing-screen + run-aborted -> resting',
  'observing-screen + run-failed -> error',
  'observing-screen + observation-finished -> thinking|resting',
  'observing-screen + speech-started -> reject(illegal-transition)',
  'observing-screen + speech-finished -> reject(illegal-transition)',
  'observing-screen + speech-stopped -> reject(illegal-transition)',
  'observing-screen + speech-failed -> reject(illegal-transition)',
  'observing-screen + failure -> error',
  'speaking + select-window -> resting | reject(window-not-found,illegal-transition)',
  'speaking + set-observation-enabled -> resting | reject(illegal-transition)',
  'speaking + push-to-talk-down -> listening | reject(illegal-transition)',
  'speaking + push-to-talk-up -> transcribing | reject(illegal-transition)',
  'speaking + submit-text -> thinking | reject(empty-input)',
  'speaking + look-now -> observing-screen | reject(illegal-transition)',
  'speaking + interrupt -> resting | reject(nothing-to-interrupt)',
  'speaking + stop-speaking -> resting | reject(nothing-to-interrupt)',
  'speaking + clear-conversation -> resting',
  'speaking + pause -> resting | reject(already-paused)',
  'speaking + resume -> resting | reject(not-paused)',
  'speaking + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'speaking + permissions-changed -> resting|same',
  'speaking + windows-changed -> same',
  'speaking + window-closed -> error',
  'speaking + screen-locked -> resting | reject(illegal-transition)',
  'speaking + screen-unlocked -> resting | reject(illegal-transition)',
  'speaking + transcript-partial -> reject(illegal-transition)',
  'speaking + transcript-final -> reject(illegal-transition)',
  'speaking + transcript-failed -> reject(illegal-transition)',
  'speaking + run-started -> same',
  'speaking + run-text-delta -> same',
  'speaking + tool-started -> observing-screen',
  'speaking + tool-finished -> reject(illegal-transition)',
  'speaking + run-completed -> speaking|resting|same',
  'speaking + run-aborted -> resting',
  'speaking + run-failed -> error',
  'speaking + observation-finished -> reject(illegal-transition)',
  'speaking + speech-started -> same',
  'speaking + speech-finished -> resting',
  'speaking + speech-stopped -> resting',
  'speaking + speech-failed -> error',
  'speaking + failure -> error',
  'error + select-window -> resting | reject(window-not-found,illegal-transition)',
  'error + set-observation-enabled -> resting | reject(illegal-transition)',
  'error + push-to-talk-down -> reject(illegal-transition)',
  'error + push-to-talk-up -> reject(illegal-transition)',
  'error + submit-text -> reject(illegal-transition)',
  'error + look-now -> reject(illegal-transition)',
  'error + interrupt -> reject(nothing-to-interrupt)',
  'error + stop-speaking -> reject(nothing-to-interrupt)',
  'error + clear-conversation -> resting',
  'error + pause -> resting | reject(already-paused)',
  'error + resume -> resting | reject(not-paused)',
  'error + dismiss-error -> resting|same | reject(nothing-to-dismiss)',
  'error + permissions-changed -> resting|same',
  'error + windows-changed -> same',
  'error + window-closed -> error',
  'error + screen-locked -> resting | reject(illegal-transition)',
  'error + screen-unlocked -> resting | reject(illegal-transition)',
  'error + transcript-partial -> reject(illegal-transition)',
  'error + transcript-final -> reject(illegal-transition)',
  'error + transcript-failed -> reject(illegal-transition)',
  'error + run-started -> reject(illegal-transition)',
  'error + run-text-delta -> reject(illegal-transition)',
  'error + tool-started -> reject(illegal-transition)',
  'error + tool-finished -> reject(illegal-transition)',
  'error + run-completed -> reject(illegal-transition)',
  'error + run-aborted -> reject(illegal-transition)',
  'error + run-failed -> reject(illegal-transition)',
  'error + observation-finished -> reject(illegal-transition)',
  'error + speech-started -> reject(illegal-transition)',
  'error + speech-finished -> reject(illegal-transition)',
  'error + speech-stopped -> reject(illegal-transition)',
  'error + speech-failed -> reject(illegal-transition)',
  'error + failure -> error',
];
