import {
  createModels,
  fauxAssistantMessage,
  fauxProvider,
  fauxToolCall,
  type Api,
  type AssistantMessage,
  type Context,
  type Model,
  type Models,
} from '@earendil-works/pi-ai';
import type { ModelProfile } from '@pilot/shared';
import { toModelProfileWithProvenance } from './model-profile.js';
import type { CapabilityConfidence } from './capability.js';

/**
 * The development model source (ADDED BY PR-029).
 *
 * **There is no model access in this environment.** `docs/handoff.md` §2: the
 * user chose Codex subscription, no sign-in has happened, and there is no API
 * key on the development machine — so no live provider call has ever been made,
 * and none can be made here. Runbook amendment 2 and 7 record the consequence:
 * Phase 3 integration (PR-029…PR-036) is *built* against a development profile
 * and *demonstrated* against a faux provider until that sign-in happens.
 *
 * This module is that development profile, in one place, so the app does not
 * have to grow its own copy of it. It produces a `Models` collection backed by
 * Pi's own built-in faux provider — the same `fauxProvider` PR-005's spike and
 * every agent-lane test uses — which speaks the real `Models`/`Model` API.
 *
 * **What that does and does not prove.** Everything above the provider is the
 * shipping code path: the capability gate, `Agent.prompt`, streamed text
 * deltas, tool calls, `waitForIdle`, abort, pruning, compaction. What it is not
 * is a language model — the answers are generated by {@link answerFor}, in this
 * file, and they say so in their own text. Provider-side image encoding, real
 * streaming timing and compaction summary quality are exactly what
 * `docs/handoff.md` §2 says the mock cannot show.
 *
 * PR-037…PR-039 add the real providers. When they do, the only thing that has
 * to change is which source the app asks for.
 */

/** Development model fixtures. `faux` is the one the app boots into. */
export const DEVELOPMENT_MODEL_FIXTURES = ['faux', 'faux-text-only', 'faux-no-tools'] as const;

export type DevelopmentModelFixture = (typeof DEVELOPMENT_MODEL_FIXTURES)[number];

/**
 * Parses a fixture name, falling back to the vision-capable one.
 *
 * `PILOT_MODEL_FIXTURE=faux-text-only pnpm dev` is how a reviewer reaches the
 * capability gate's refusal without editing source: a model whose `Model.input`
 * carries no `"image"` is refused *before* Pi's `Agent` is constructed, which is
 * the whole point of PR-020 — a non-vision model does not error on an image, it
 * silently ignores it.
 */
export function resolveDevelopmentModelFixture(raw: string | undefined): DevelopmentModelFixture {
  return (DEVELOPMENT_MODEL_FIXTURES as readonly string[]).includes(raw ?? '')
    ? (raw as DevelopmentModelFixture)
    : 'faux';
}

/** Everything `new PiAgentSession(...)` needs in order to name a model. */
export interface ModelSource {
  readonly profile: ModelProfile;
  readonly models: Models;
  readonly model: Model<Api>;
  /** Whether `profile.supportsTools` was configured or defaulted (PR-020). */
  readonly toolSupport: CapabilityConfidence;
  /**
   * Provider requests served so far.
   *
   * Zero after a refused profile is what "the capability gate refused *before
   * anything was sent*" means, stated as a number a test can assert on rather
   * than as a claim about control flow.
   */
  requestCount(): number;
  /** One line for a log or a demo header. Never contains screen content. */
  readonly description: string;
}

export interface DevelopmentModelSource extends ModelSource {
  readonly fixture: DevelopmentModelFixture;
}

/** First line of a rendered envelope is the user's own words (system-design §8). */
function questionFrom(context: Context): string {
  for (let index = context.messages.length - 1; index >= 0; index -= 1) {
    const message = context.messages[index];
    if (message === undefined || message.role !== 'user') {
      continue;
    }
    const text =
      typeof message.content === 'string'
        ? message.content
        : message.content
            .filter(
              (block): block is Extract<typeof block, { type: 'text' }> => block.type === 'text',
            )
            .map((block) => block.text)
            .join('');
    const [first] = text.split('\n');
    if (first !== undefined && first.trim() !== '') {
      return first.trim();
    }
  }
  return 'your question';
}

/**
 * The faux answer.
 *
 * Several sentences on purpose: the response buffer (PR-026) releases one
 * completed sentence at a time, so a one-sentence answer would never show the
 * panel filling in as the answer grows. It quotes the question and numbers the
 * turn, which is what makes "turn three answered turn three's question" visible
 * rather than merely asserted.
 */
export function answerFor(turn: number, question: string): string {
  return (
    `Turn ${String(turn)}: you asked “${question}”. ` +
    'This reply comes from Pi’s built-in faux provider, not from a language model, ' +
    'so no request left this machine and no credentials were used. ' +
    'Everything above the provider is the real path: the capability gate, the question ' +
    'envelope, the Pi agent loop, and the streamed deltas that filled this line in.'
  );
}

export interface DevelopmentModelSourceOptions {
  readonly fixture?: DevelopmentModelFixture;
  /**
   * How fast the faux provider streams. The default is slow enough that a
   * reviewer watches an answer arrive a clause at a time, and slow enough for
   * an interruption to land in the middle of one.
   */
  readonly tokensPerSecond?: number;
}

/**
 * A `Models` collection backed only by the faux provider.
 *
 * The queued response step **re-arms itself**. Pi's faux provider consumes one
 * queued response per request, so a fixed script would answer a fixed number of
 * turns and then fail with "No more faux responses queued" — which would look
 * exactly like the multi-turn defect PR-022a fixed (`agent_end` firing before
 * `prompt()` unwinds). Appending the next step from inside the current one means
 * the source answers indefinitely, so a failure on turn four is a real failure.
 */
export function createDevelopmentModelSource(
  options: DevelopmentModelSourceOptions = {},
): DevelopmentModelSource {
  const fixture = options.fixture ?? 'faux';
  const vision = fixture !== 'faux-text-only';
  const faux = fauxProvider({
    provider: 'pilot-faux',
    models: [
      {
        id: vision ? 'faux-vision' : 'faux-text-only',
        input: vision ? ['text', 'image'] : ['text'],
      },
    ],
    tokensPerSecond: options.tokensPerSecond ?? 40,
  });
  const models = createModels();
  models.setProvider(faux.provider);
  const model = faux.getModel();

  let turn = 0;
  const step = (context: Context): AssistantMessage => {
    turn += 1;
    faux.appendResponses([step]);
    return fauxAssistantMessage(answerFor(turn, questionFrom(context)), { stopReason: 'stop' });
  };
  faux.setResponses([step]);

  const { profile, toolSupport } = toModelProfileWithProvenance(model, {
    id: `profile-${fixture}`,
    authMode: 'local',
    supportsTools: fixture !== 'faux-no-tools',
  });

  return {
    fixture,
    profile,
    models,
    model,
    toolSupport,
    requestCount: () => faux.state.callCount,
    description:
      `Pi faux provider (${profile.provider}/${profile.model}, fixture “${fixture}”) — ` +
      'no network, no credentials, not a language model',
  };
}

// ---------------------------------------------------------------------------
// A scripted source, for tests and demos (PR-029)
// ---------------------------------------------------------------------------

/** One provider reply: say something, or call `observe_screen` first. */
export type ScriptedStep =
  | { readonly say: string }
  | {
      readonly observe: {
        readonly view: 'pointer' | 'window' | 'both';
        readonly moment: 'question' | 'current' | 'before-and-after';
      };
    };

export interface ScriptedModelSource extends ModelSource {
  /**
   * JSON of the messages each provider request carried, oldest first.
   *
   * A string rather than Pi's `Context` so a caller outside this package can
   * assert on what the model was actually sent — the rendered envelope, the
   * tool results, the pruned image blocks — without importing a Pi type.
   */
  readonly requests: readonly string[];
  setScript(steps: readonly ScriptedStep[]): void;
}

/**
 * A faux source whose every reply is chosen by the caller.
 *
 * {@link createDevelopmentModelSource} answers every question the same way,
 * which is right for the app and useless for a test that needs the model to
 * call a tool, or to say one exact sentence. This is the same faux provider
 * with the script left open, and it keeps `@earendil-works/pi-ai` inside this
 * package: `apps/desktop` has no Pi dependency and should not grow one.
 *
 * The script does not repeat. Running past its end is a provider error
 * ("No more faux responses queued"), which is the correct outcome for a test
 * that miscounted its turns.
 */
export function createScriptedModelSource(
  options: {
    readonly vision?: boolean;
    readonly tools?: boolean;
    readonly tokensPerSecond?: number;
    readonly script?: readonly ScriptedStep[];
  } = {},
): ScriptedModelSource {
  const vision = options.vision ?? true;
  const faux = fauxProvider({
    provider: 'pilot-faux',
    models: [{ id: 'faux-scripted', input: vision ? ['text', 'image'] : ['text'] }],
    ...(options.tokensPerSecond === undefined ? {} : { tokensPerSecond: options.tokensPerSecond }),
  });
  const models = createModels();
  models.setProvider(faux.provider);
  const model = faux.getModel();
  const requests: string[] = [];

  const setScript = (steps: readonly ScriptedStep[]): void => {
    faux.setResponses(
      steps.map((step) => (context: Context) => {
        // Tools carry functions, so only the messages can be serialized.
        requests.push(JSON.stringify(context.messages));
        return 'say' in step
          ? fauxAssistantMessage(step.say, { stopReason: 'stop' })
          : fauxAssistantMessage([fauxToolCall('observe_screen', step.observe)], {
              stopReason: 'toolUse',
            });
      }),
    );
  };
  setScript(options.script ?? []);

  const { profile, toolSupport } = toModelProfileWithProvenance(model, {
    id: 'profile-scripted',
    authMode: 'local',
    supportsTools: options.tools ?? true,
  });

  return {
    profile,
    models,
    model,
    toolSupport,
    requests,
    setScript,
    requestCount: () => faux.state.callCount,
    description: `Pi faux provider (scripted, ${profile.provider}/${profile.model})`,
  };
}
