import { describe, expect, it } from 'vitest';
import { asConversationId, asObservationId } from '@pilot/shared';
import type { PilotViewState } from '@pilot/platform';
import {
  FakeScreenContextService,
  FIXTURE_WINDOW_RETINA,
  createFixtureObservation,
} from '@pilot/platform/fakes';
import {
  createDevelopmentModelSource,
  createScriptedModelSource,
  type ModelSource,
  type PiAgentSession,
} from '@pilot/agent';
import type { PilotInteractionController } from '@pilot/interaction';
import { createAgentRuntime, type AgentRuntime } from '../../src/main/agent-runtime.js';
import { createInteractionRuntime } from '../../src/main/interaction-runtime.js';

/**
 * PR-029 — a text conversation with a **real** Pi session.
 *
 * Everything below runs the shipping path: `main/index.ts`'s own
 * `createAgentRuntime` and `createInteractionRuntime`, the real
 * `PilotInteractionController`, the real `PiAgentSession`, the real capability
 * gate, real streaming deltas, a real abort.
 *
 * **What is not real: the provider.** There is no model access on this machine
 * (`docs/handoff.md` §2) — the user chose Codex subscription, no sign-in has
 * happened, and there is no API key — so the model is Pi's built-in faux
 * provider and the words in the answers are generated by
 * `@pilot/agent`'s `answerFor`. What the faux provider *cannot* show is
 * provider-side image encoding, real streaming timing, and compaction summary
 * quality. Everything above it is the code that ships.
 *
 * Speech and observation are still mocked. That is deliberate: an integration
 * PR replaces one fake boundary at a time (`docs/implementation.md`), and this
 * one's boundary is the agent.
 */

const CONVERSATION = asConversationId('conv-pr029-test');

interface Rig {
  readonly runtime: AgentRuntime;
  readonly controller: PilotInteractionController;
  readonly source: ModelSource;
  dispose(): Promise<void>;
}

function rig(
  options: {
    readonly fixture?: Parameters<typeof createDevelopmentModelSource>[0] extends infer T
      ? T extends { fixture?: infer F }
        ? F
        : never
      : never;
    readonly tokensPerSecond?: number;
    readonly source?: ModelSource;
    readonly screenContext?: FakeScreenContextService;
  } = {},
): Rig {
  const source =
    options.source ??
    createDevelopmentModelSource({
      ...(options.fixture === undefined ? {} : { fixture: options.fixture }),
      ...(options.tokensPerSecond === undefined
        ? {}
        : { tokensPerSecond: options.tokensPerSecond }),
    });
  const runtime = createAgentRuntime({
    conversationId: CONVERSATION,
    source,
    ...(options.screenContext === undefined ? {} : { screenContext: options.screenContext }),
  });
  const { controller } = createInteractionRuntime({
    agent: runtime.session,
    conversationId: CONVERSATION,
  });
  return {
    runtime,
    controller,
    source,
    dispose: async () => {
      await controller.dispose();
      await runtime.dispose();
    },
  };
}

const RESTING = new Set<PilotViewState['state']>(['idle', 'observing', 'paused', 'error']);

/** Waits for the run to finish. Bounded, so a wedged run fails rather than hangs. */
async function settle(controller: PilotInteractionController): Promise<void> {
  await controller.settled();
  const deadline = Date.now() + 10_000;
  while (!RESTING.has(controller.snapshot().state)) {
    if (Date.now() > deadline) {
      throw new Error(`run never settled; stuck in ${controller.snapshot().state}`);
    }
    await new Promise((resolve) => setTimeout(resolve, 5));
  }
  await controller.settled();
}

function assistantTurns(view: PilotViewState): readonly PilotViewState['transcript'][number][] {
  return view.transcript.filter((entry) => entry.role === 'assistant');
}

describe('a multi-turn text conversation against a real Pi session', () => {
  it('answers three questions in a row, each one about the question that was asked', async () => {
    const test = rig();

    const questions = [
      'What does this Auto Renew toggle do?',
      'And what happens if I turn it off?',
      'Where do I find the invoices?',
    ];
    for (const question of questions) {
      test.controller.dispatch({ type: 'submit-text', text: question });
      await settle(test.controller);
    }

    const view = test.controller.snapshot();
    const answers = assistantTurns(view);

    // The defect PR-022a fixed lives exactly here: `agent_end` fires before
    // `Agent.prompt()` unwinds, so before that fix turn two failed with
    // "Agent is already processing a prompt" and every turn after it did too.
    expect(view.lastError).toBeNull();
    expect(answers).toHaveLength(3);
    expect(view.transcript.filter((entry) => entry.role === 'user')).toHaveLength(3);

    // Each answer names its own turn and quotes its own question, so "three
    // turns happened" is not the same claim as "the third answer answered the
    // third question".
    answers.forEach((answer, index) => {
      expect(answer.text).toContain(`Turn ${String(index + 1)}:`);
      expect(answer.text).toContain(questions[index] ?? '');
      expect(answer.pending).toBe(false);
    });

    // One provider request per turn: no retries, no hidden extra round trip.
    expect(test.source.requestCount()).toBe(3);

    await test.dispose();
    // Three streamed answers at the development source's own rate; the ceiling
    // is generous so a slow machine reports a slow machine, not a defect.
  }, 30_000);

  it('renders the answer as it grows, not only when it is finished', async () => {
    // Slow enough that several deltas land while the panel is subscribed.
    const test = rig({ tokensPerSecond: 60 });
    const lengths: number[] = [];
    const pendingWhileGrowing: boolean[] = [];

    test.controller.subscribe((view) => {
      const newest = view.transcript.at(-1);
      if (newest?.role === 'assistant') {
        lengths.push(newest.text.length);
        pendingWhileGrowing.push(newest.pending);
      }
    });

    test.controller.dispatch({ type: 'submit-text', text: 'What does this do?' });
    await settle(test.controller);

    // The panel saw the answer at several sizes, each larger than the last —
    // which is what "streams into the panel" means at the view-state level.
    expect(lengths.length).toBeGreaterThan(2);
    for (let index = 1; index < lengths.length; index += 1) {
      expect(lengths[index]).toBeGreaterThanOrEqual(lengths[index - 1] ?? 0);
    }
    expect(lengths.at(-1)).toBeGreaterThan(lengths[0] ?? 0);
    // It was marked pending while it was still arriving, and not at the end.
    expect(pendingWhileGrowing[0]).toBe(true);
    expect(pendingWhileGrowing.at(-1)).toBe(false);

    await test.dispose();
  }, 30_000);

  it('stops mid-answer when the user interrupts, and keeps what had arrived', async () => {
    const test = rig({ tokensPerSecond: 30 });

    test.controller.dispatch({ type: 'submit-text', text: 'Tell me about this screen.' });
    await test.controller.settled();

    // Wait until the model has actually said something, so this is an
    // interruption rather than a cancellation before the run produced anything.
    const deadline = Date.now() + 10_000;
    const partialArrived = (): boolean => {
      const newest = test.controller.snapshot().transcript.at(-1);
      return newest?.role === 'assistant' && newest.text.length > 0;
    };
    while (!partialArrived()) {
      if (Date.now() > deadline) {
        throw new Error('the answer never started');
      }
      await new Promise((resolve) => setTimeout(resolve, 5));
    }
    const partial = assistantTurns(test.controller.snapshot()).at(-1);
    expect(partial).toBeDefined();

    test.controller.dispatch({ type: 'interrupt' });
    await settle(test.controller);

    const view = test.controller.snapshot();
    const interrupted = assistantTurns(view).at(-1);
    // The half-finished answer stays on screen. It is still `pending`, which is
    // what the panel renders as "interrupted" (PR-010's view model).
    expect(interrupted?.text.startsWith(partial?.text ?? '')).toBe(true);
    expect(interrupted?.text.length).toBeLessThan(300);
    expect(interrupted?.pending).toBe(true);
    // An interruption is not a failure (system-design §15).
    expect(view.lastError).toBeNull();
    expect(RESTING.has(view.state)).toBe(true);

    // And the session is not wedged: the next question still gets an answer,
    // which is the property an abort is most likely to break.
    test.controller.dispatch({ type: 'submit-text', text: 'Never mind — what is this page?' });
    await settle(test.controller);
    const after = assistantTurns(test.controller.snapshot()).at(-1);
    expect(after?.pending).toBe(false);
    expect(after?.text).toContain('what is this page?');
    expect(test.controller.snapshot().lastError).toBeNull();

    await test.dispose();
  }, 30_000);
});

describe('the capability gate refuses before anything is sent', () => {
  it('refuses a model with no image input, having made no provider request', async () => {
    const source = createDevelopmentModelSource({ fixture: 'faux-text-only' });
    const runtime = createAgentRuntime({ conversationId: CONVERSATION, source });

    expect(runtime.capability.ok).toBe(false);
    expect(runtime.capability.ok === false && runtime.capability.error.code).toBe(
      'unsupported-capability',
    );
    expect(runtime.capability.ok === false && runtime.capability.error.userMessage).toContain(
      'cannot see images',
    );
    // The gate runs in `PiAgentSession`'s constructor, before Pi's `Agent`
    // exists. Nothing was asked of the provider — this is the number that says
    // so, rather than an argument about control flow.
    expect(source.requestCount()).toBe(0);

    await runtime.dispose();
  });

  it('refuses a model configured without tools', async () => {
    const source = createDevelopmentModelSource({ fixture: 'faux-no-tools' });
    const runtime = createAgentRuntime({ conversationId: CONVERSATION, source });

    expect(runtime.capability.ok === false && runtime.capability.error.code).toBe(
      'unsupported-capability',
    );
    expect(source.requestCount()).toBe(0);

    await runtime.dispose();
  });

  it('tells the user why, and still never sends the question', async () => {
    const test = rig({ fixture: 'faux-text-only' });

    test.controller.dispatch({ type: 'submit-text', text: 'What does this toggle do?' });
    await settle(test.controller);

    const view = test.controller.snapshot();
    expect(view.state).toBe('error');
    expect(view.lastError?.code).toBe('unsupported-capability');
    // system-design §16: the user is told what happened and what to do.
    expect(view.lastError?.userMessage).toContain('Pick a different model');
    expect(test.source.requestCount()).toBe(0);

    await test.dispose();
  });
});

describe('the wirings PR-029 owed (docs/runbook.md §8)', () => {
  it('renders the envelope with the anchored renderer, not as a pointer at -1, -1', async () => {
    // Follow-up 1. With observation mocked there is no recorded pointer, so
    // every envelope is `grounding: 'pointer-unknown'` — the exact case where
    // `@pilot/agent`'s own renderer would print `pointer: -1.000, -1.000`.
    const source = createScriptedModelSource({ script: [{ say: 'Understood.' }] });
    const test = rig({ source });
    // A window has to be selected, or the envelope's grounding is
    // `no-selected-window` and the pointer question never arises.
    test.controller.send({ type: 'windows-changed', windows: [FIXTURE_WINDOW_RETINA] });
    test.controller.dispatch({
      type: 'select-window',
      windowId: FIXTURE_WINDOW_RETINA.windowId,
    });

    test.controller.dispatch({ type: 'submit-text', text: 'What is this?' });
    await settle(test.controller);

    const rendered = source.requests[0] ?? '';
    expect(rendered).toContain('pointer: unknown');
    expect(rendered).not.toContain('-1.000');

    await test.dispose();
  }, 30_000);

  it('writes every observation into the notebook and reads it back when pruning', async () => {
    // Follow-up 4, both halves. `createObserveScreenTool({ onObservation })`
    // fills the notebook; `visualContext.summaryFor` is what turns a pruned
    // frame into a truthful record instead of "No description of that frame was
    // recorded."
    const screenContext = new FakeScreenContextService({
      observations: [1, 2, 3].map((n) =>
        createFixtureObservation({
          observationId: asObservationId(`obs-000${String(n)}`),
          sceneRevision: n,
        }),
      ),
    });
    const look = { observe: { view: 'window', moment: 'question' } } as const;
    const say = { say: 'That is what is on screen.' } as const;
    const source = createScriptedModelSource({
      script: [look, say, look, say, look, say],
    });
    const test = rig({ screenContext, source });

    for (const question of ['What is this?', 'And now?', 'And now?']) {
      test.controller.dispatch({ type: 'submit-text', text: question });
      await settle(test.controller);
    }

    // Half one: the tool wrote each observation down.
    expect(screenContext.requests).toHaveLength(3);
    expect(test.runtime.notebook.size).toBe(3);

    // Half two: the session read them back. The provider-facing context keeps
    // the newest frame and replaces the older ones with the notebook's own
    // past-tense record, which names the scene it described.
    const session = test.runtime.session as PiAgentSession;
    const active = JSON.stringify(session.activeContext());
    expect(active).toContain('This is a past record of');
    expect(active).not.toContain('No description of that frame was recorded');

    await test.dispose();
  }, 30_000);
});
