import { asConversationId } from '@pilot/shared';
import type { PilotViewState } from '@pilot/platform';
import { createDevelopmentModelSource } from '@pilot/agent';
import type { PilotInteractionController } from '@pilot/interaction';
import { createAgentRuntime } from './agent-runtime.js';
import { createInteractionRuntime } from './interaction-runtime.js';

/**
 * PR-029's demo: a multi-turn text conversation with a real Pi session.
 *
 * `docs/implementation.md` PR-029 asks for "a multi-turn text conversation with
 * a configured model". This is that conversation, run headlessly through the
 * exact composition `main/index.ts` uses — `createAgentRuntime` and
 * `createInteractionRuntime`, no test doubles above the ports.
 *
 * ## What is real here and what is not
 *
 * REAL: the interaction state machine and its transition table; the question
 * envelope, rendered by `renderAnchoredQuestionEnvelope`; `PiAgentSession` over
 * Pi's own `Agent`; the capability gate; streamed text deltas; `Agent.abort()`;
 * the multi-turn fix from PR-022a.
 *
 * NOT REAL: **the model**. There is no model access on this machine
 * (`docs/handoff.md` §2: the user chose Codex subscription, no sign-in has
 * happened, no API key exists), so the provider is Pi's built-in faux provider
 * and the sentences in the answers are generated by `@pilot/agent`'s
 * `answerFor`. Speech is mocked (PR-032/033) and observation is mocked
 * (PR-028/030) — no screen is read and no sound is made.
 *
 * The four things a reviewer should look for are printed as sections: three
 * turns in a row, an answer arriving in pieces, an interruption mid-answer, and
 * the capability gate refusing a model before anything is sent.
 */

export interface AgentDemoResult {
  readonly lines: readonly string[];
  /** Turns that completed with an answer. */
  readonly turns: number;
  /** Provider requests made while the capability gate was refusing. */
  readonly requestsWhileRefused: number;
}

const CONVERSATION = asConversationId('conv-agent-demo');

function heading(title: string): string {
  return `\n── ${title} ${'─'.repeat(Math.max(0, 62 - title.length))}`;
}

function wrap(text: string, width = 72, indent = '    '): string[] {
  const words = text.split(/\s+/u);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if (current === '') {
      current = word;
    } else if (current.length + word.length + 1 <= width) {
      current = `${current} ${word}`;
    } else {
      lines.push(indent + current);
      current = word;
    }
  }
  if (current !== '') {
    lines.push(indent + current);
  }
  return lines;
}

const RESTING = new Set<PilotViewState['state']>(['idle', 'observing', 'paused', 'error']);

async function settle(controller: PilotInteractionController, timeoutMs = 20_000): Promise<void> {
  await controller.settled();
  const deadline = Date.now() + timeoutMs;
  while (!RESTING.has(controller.snapshot().state)) {
    if (Date.now() > deadline) {
      throw new Error(`the run never settled; stuck in ${controller.snapshot().state}`);
    }
    await new Promise((resolve) => setTimeout(resolve, 5));
  }
  await controller.settled();
}

export async function runAgentDemo(): Promise<AgentDemoResult> {
  const lines: string[] = [];
  lines.push('Pilot — text conversation with a real Pi session (PR-029)');

  // -------------------------------------------------------------------------
  // 1. The model behind the conversation, said out loud.
  // -------------------------------------------------------------------------
  const source = createDevelopmentModelSource({ tokensPerSecond: 120 });
  lines.push(heading('the model'));
  lines.push(`  ${source.description}`);
  lines.push(
    `  profile ${source.profile.provider}/${source.profile.model} · vision ` +
      `${String(source.profile.supportsVision)} · tools ${String(source.profile.supportsTools)} ` +
      `· remote ${String(source.profile.isRemote)}`,
  );
  lines.push('  Everything above the provider is the code that ships. The answers are not.');

  const runtime = createAgentRuntime({ conversationId: CONVERSATION, source });
  const { controller, observation } = createInteractionRuntime({
    agent: runtime.session,
    conversationId: CONVERSATION,
  });
  lines.push(
    `  capability gate: ${runtime.capability.ok ? 'passed' : 'REFUSED'} · vision ` +
      `${String(runtime.capability.ok && runtime.capability.report.vision)} · tools ` +
      `${String(runtime.capability.ok && runtime.capability.report.tools)}`,
  );

  // -------------------------------------------------------------------------
  // 2. Three turns in a row. This is what PR-022a's defect broke.
  // -------------------------------------------------------------------------
  lines.push(heading('three turns in a row'));
  const questions = [
    'What does this Auto Renew toggle actually do?',
    'And what happens if I turn it off?',
    'Where would I find the invoices for it?',
  ];
  let turns = 0;
  for (const question of questions) {
    controller.dispatch({ type: 'submit-text', text: question });
    await settle(controller);
    const view = controller.snapshot();
    const answer = view.transcript.at(-1);
    lines.push(`  you  : ${question}`);
    if (answer?.role === 'assistant') {
      lines.push('  pilot:');
      lines.push(...wrap(answer.text));
      if (!answer.pending) {
        turns += 1;
      }
    }
    lines.push(
      `  state: ${view.state} · error ${view.lastError === null ? 'none' : view.lastError.code}` +
        ` · provider requests so far ${String(source.requestCount())}`,
    );
    lines.push('');
  }
  lines.push(
    `  ${String(turns)} turns completed. Before PR-022a's fix the second question failed with`,
  );
  lines.push('  "Agent is already processing a prompt", and every question after it did too.');

  // -------------------------------------------------------------------------
  // 3. The answer arriving in pieces.
  // -------------------------------------------------------------------------
  lines.push(heading('the answer arrives as it is written'));
  const sizes: number[] = [];
  const unsubscribe = controller.subscribe((view) => {
    const newest = view.transcript.at(-1);
    if (newest?.role === 'assistant' && newest.pending) {
      sizes.push(newest.text.length);
    }
  });
  controller.dispatch({ type: 'submit-text', text: 'Say that again, slowly.' });
  await settle(controller);
  unsubscribe();
  lines.push(
    `  the panel re-rendered ${String(sizes.length)} times while the answer grew, at ` +
      `${sizes.slice(0, 8).join(', ')}${sizes.length > 8 ? ', …' : ''} characters`,
  );
  lines.push(
    '  Each of those is a `text-delta` reaching the transition table as a new view state.',
  );

  // -------------------------------------------------------------------------
  // 4. Interruption mid-answer.
  // -------------------------------------------------------------------------
  lines.push(heading('interrupted mid-answer'));
  controller.dispatch({ type: 'submit-text', text: 'Tell me everything about this window.' });
  await controller.settled();
  const startedBy = Date.now() + 20_000;
  const partialText = (): string => {
    const newest = controller.snapshot().transcript.at(-1);
    return newest?.role === 'assistant' ? newest.text : '';
  };
  while (partialText() === '') {
    if (Date.now() > startedBy) {
      throw new Error('the answer never started');
    }
    await new Promise((resolve) => setTimeout(resolve, 5));
  }
  const beforeInterrupt = partialText().length;
  controller.dispatch({ type: 'interrupt' });
  await settle(controller);
  const interrupted = controller.snapshot().transcript.at(-1);
  lines.push(`  interrupted after ${String(beforeInterrupt)} characters had arrived`);
  lines.push(`  what stayed on screen (${String(interrupted?.text.length ?? 0)} characters):`);
  lines.push(...wrap(interrupted?.text ?? ''));
  lines.push(
    `  still marked pending: ${String(interrupted?.pending ?? false)} — the panel renders that as` +
      ' "interrupted"',
  );
  lines.push(
    `  lastError: ${controller.snapshot().lastError === null ? 'none' : 'SET'} — an interruption is not a failure (§15)`,
  );

  // The property an abort is most likely to break.
  controller.dispatch({ type: 'submit-text', text: 'Sorry — what is this page?' });
  await settle(controller);
  const recovered = controller.snapshot().transcript.at(-1);
  lines.push(
    `  the next question still gets an answer: ${String(recovered?.pending === false)} ` +
      `(${String(recovered?.text.length ?? 0)} characters)`,
  );

  lines.push(heading('what the mocked ports were asked for'));
  lines.push(`  capture lifecycle calls: ${(observation.calls ?? []).join(', ') || 'none'}`);
  lines.push('  Nothing was captured: PR-028 brings the real adapter, PR-030 the real tool.');

  await controller.dispose();
  await runtime.dispose();

  // -------------------------------------------------------------------------
  // 5. The capability gate, refusing.
  // -------------------------------------------------------------------------
  lines.push(heading('the capability gate refuses before anything is sent'));
  const textOnly = createDevelopmentModelSource({ fixture: 'faux-text-only' });
  const refused = createAgentRuntime({ conversationId: CONVERSATION, source: textOnly });
  const { controller: refusedController } = createInteractionRuntime({
    agent: refused.session,
    conversationId: CONVERSATION,
  });
  lines.push(`  model: ${textOnly.description}`);
  lines.push(
    `  gate : ${refused.capability.ok ? 'passed' : `refused — ${refused.capability.error.code}`}`,
  );
  if (!refused.capability.ok) {
    lines.push(...wrap(refused.capability.error.userMessage, 72, '         '));
  }
  refusedController.dispatch({ type: 'submit-text', text: 'What does this toggle do?' });
  await settle(refusedController);
  const requestsWhileRefused = textOnly.requestCount();
  lines.push(`  the panel now says: ${refusedController.snapshot().lastError?.code ?? 'nothing'}`);
  lines.push(
    `  provider requests made: ${String(requestsWhileRefused)} — the gate runs in ` +
      "`PiAgentSession`'s",
  );
  lines.push('  constructor, before Pi’s Agent exists, so a refusal costs nothing.');
  await refusedController.dispose();
  await refused.dispose();

  lines.push('');
  return { lines, turns, requestsWhileRefused };
}
